import type { Product } from './types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Velvet Glow Foundation',
    brand: 'Aura Beauty',
    description: 'A lightweight, buildable foundation that provides a natural, radiant finish. Formulated with hyaluronic acid for all-day hydration.',
    price: 38.00,
    category: 'Makeup',
    image: 'https://placehold.co/400x400.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    ingredients: ['Water', 'Cyclopentasiloxane', 'Titanium Dioxide', 'Hyaluronic Acid'],
    usage: 'Apply with a sponge or brush, blending from the center of the face outwards.',
    rating: 4.5,
    reviewCount: 125,
  },
  {
    id: '2',
    name: 'Hydra-Boost Serum',
    brand: 'Pure Elements',
    description: 'A powerful hydrating serum that plumps and smooths the skin, reducing the appearance of fine lines. Perfect for all skin types.',
    price: 52.00,
    category: 'Skincare',
    image: 'https://placehold.co/400x400.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    ingredients: ['Hyaluronic Acid', 'Vitamin B5', 'Glycerin', 'Aloe Vera'],
    usage: 'Apply 2-3 drops to clean skin morning and night before moisturizing.',
    rating: 4.8,
    reviewCount: 230,
  },
  {
    id: '3',
    name: 'Rose Noir Eau de Parfum',
    brand: 'Maison de Senteur',
    description: 'An alluring and sophisticated fragrance with notes of black rose, oud, and a hint of pink pepper.',
    price: 120.00,
    category: 'Fragrance',
    image: 'https://placehold.co/400x400.png',
    images: ['https://placehold.co/600x600.png'],
    ingredients: ['Alcohol Denat.', 'Parfum (Fragrance)', 'Water', 'Linalool'],
    usage: 'Spritz onto pulse points such as wrists, neck, and behind the ears.',
    rating: 4.9,
    reviewCount: 98,
  },
  {
    id: '4',
    name: 'Silk Finish Lipstick',
    brand: 'Aura Beauty',
    description: 'A creamy, long-wearing lipstick with a satin finish. Available in 12 vibrant shades.',
    price: 24.00,
    category: 'Makeup',
    image: 'https://placehold.co/400x400.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    ingredients: ['Shea Butter', 'Vitamin E', 'Jojoba Oil', 'Pigment'],
    usage: 'Apply directly to lips or use a lip brush for more precision.',
    rating: 4.6,
    reviewCount: 180,
  },
  {
    id: '5',
    name: 'Argan Oil Hair Repair',
    brand: 'Luxe Locks',
    description: 'A nourishing hair oil that tames frizz, adds shine, and protects against heat damage. Infused with pure Argan oil from Morocco.',
    price: 32.00,
    category: 'Haircare',
    image: 'https://placehold.co/400x400.png',
    images: ['https://placehold.co/600x600.png'],
    ingredients: ['Argania Spinosa (Argan) Kernel Oil', 'Cyclomethicone', 'Dimethicone'],
    usage: 'Apply a small amount to damp or dry hair, focusing on the ends.',
    rating: 4.7,
    reviewCount: 155,
  },
  {
    id: '6',
    name: 'Gentle Cleansing Foam',
    brand: 'Pure Elements',
    description: 'A mild, soap-free cleanser that effectively removes impurities without stripping the skin\'s natural moisture.',
    price: 28.00,
    category: 'Skincare',
    image: 'https://placehold.co/400x400.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    ingredients: ['Green Tea Extract', 'Chamomile', 'Glycerin', 'Cocamidopropyl Betaine'],
    usage: 'Massage one pump onto damp skin, then rinse thoroughly.',
    rating: 4.9,
    reviewCount: 310,
  },
  {
    id: '7',
    name: 'Volumizing Mascara',
    brand: 'Aura Beauty',
    description: 'A clump-free, water-resistant mascara that adds dramatic volume and length to your lashes.',
    price: 26.00,
    category: 'Makeup',
    image: 'https://placehold.co/400x400.png',
    images: ['https://placehold.co/600x600.png'],
    ingredients: ['Beeswax', 'Iron Oxides', 'Acrylates Copolymer', 'Pro-Vitamin B5'],
    usage: 'Wiggle the wand from the base of lashes to the tips. Apply a second coat for more volume.',
    rating: 4.4,
    reviewCount: 205,
  },
  {
    id: '8',
    name: 'Keratin Smooth Shampoo',
    brand: 'Luxe Locks',
    description: 'A sulfate-free shampoo that strengthens and smooths hair, leaving it soft and manageable.',
    price: 25.00,
    category: 'Haircare',
    image: 'https://placehold.co/400x400.png',
    images: ['https://placehold.co/600x600.png'],
    ingredients: ['Hydrolyzed Keratin', 'Biotin', 'Collagen', 'Argan Oil'],
    usage: 'Lather into wet hair and scalp. Rinse thoroughly. Follow with Keratin Smooth Conditioner.',
    rating: 4.6,
    reviewCount: 140,
  }
];
